//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ouatelse_CoffeeWare
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONGE
    {
        public int idConge { get; set; }
        public System.DateTime dateHeureDebut { get; set; }
        public System.DateTime dateHeureFin { get; set; }
        public string etat { get; set; }
        public int idMySalarie { get; set; }
    
        public virtual SALARIE SALARIE { get; set; }
    }
}
