//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ouatelse_CoffeeWare
{
    using System;
    using System.Collections.Generic;
    
    public partial class contient
    {
        public int idMyMagasin { get; set; }
        public int idMyProduit { get; set; }
        public int idCommande { get; set; }
        public int quantite { get; set; }
    
        public virtual STOCK STOCK { get; set; }
        public virtual PANIER PANIER { get; set; }
    }
}
