//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ouatelse_CoffeeWare
{
    using System;
    using System.Collections.Generic;
    
    public partial class travaille
    {
        public int idMagasin { get; set; }
        public System.DateTime dateDebutContrat { get; set; }
        public Nullable<System.DateTime> dateFinContrat { get; set; }
        public int idSalarie { get; set; }
    
        public virtual MAGASIN MAGASIN { get; set; }
        public virtual SALARIE SALARIE { get; set; }
    }
}
